Changed various scripts in order to accommodate the fact that GitHub plans to require authentication via personal-access tokens (PATs) instead of GitHub account passwords. Made changes to numerous scripts in order to support the use of both the HTTPS and SSH protocols for Git. Improved usage information and error messages in numerous scripts. Improved the clean-up procedures used in various scripts. Set some default time delays to zero in a few scripts.

diff --git a/bin/ari_gc_makerepo b/bin/ari_gc_makerepo
--- a/bin/ari_gc_makerepo
+++ b/bin/ari_gc_makerepo
@@ -23,12 +23,23 @@
 # 
 # __END_OF_LICENSE__
 
-cmd_dir=$(dirname "$0") || exit 1
+cmd_dir="$(dirname "$0")" || exit 1
 source "$cmd_dir/utilities" || exit 1
 
 perror()
 {
 	echo "ERROR: $@"
+}
+
+perform_cleanup()
+{
+	if [ -n "$tmp_org_name" -a -n "$tmp_repo_name" ]; then
+		eecho "deleting partially constructed repository $tmp_org_name $tmp_repo_name"
+		"$ari_gc_deleterepo" -o "$tmp_org_name" "$tmp_repo_name" 2> /dev/null
+		if [ $? -ne 0 ]; then
+			eecho "warning: cannot delete partially constructed repository"
+		fi
+	fi
 }
 
 usage()
@@ -37,6 +48,11 @@ usage()
 		echo "$@" 1>&2
 	fi
 	cat <<- EOF
+	$(basename $0)
+	Create a new Git repository on GitHub and populate the repository
+	with particular content.
+	A repository is created for each input source.
+
 	Usage
 	=====
 
@@ -63,17 +79,31 @@ usage()
 ari_gc_createrepo="$cmd_dir/ari_gc_createrepo"
 ari_gc_deleterepo="$cmd_dir/ari_gc_deleterepo"
 ari_git_makerepo="$cmd_dir/ari_git_makerepo"
+ari_gc_getcred="$cmd_dir/ari_gc_getcred"
 
 verbose=0
 org_name=
 debug_level=0
 input_type=
-check_ssh_key=1
+git_proto=ssh
+repo=
 
-while getopts ZD:o:vqt: option; do
+while getopts D:o:vqt:g:n: option; do
 	case "$option" in
 	D)
 		debug_level="$OPTARG";;
+	n)
+		repo="$OPTARG";;
+	g)
+		case "$OPTARG" in
+		http|https|ssh)
+			;;
+		*)
+			usage "invalid Git protocol"
+			;;
+		esac
+		git_proto="$OPTARG"
+		;;
 	o)
 		org_name="$OPTARG";;
 	t)
@@ -82,8 +112,6 @@ while getopts ZD:o:vqt: option; do
 		verbose=$((verbose + 1));;
 	q)
 		verbose=$((verbose - 1));;
-	Z)
-		check_ssh_key=0;;
 	*)
 		usage "invalid option $option";;
 	esac
@@ -100,11 +128,15 @@ if [ "$debug_level" -ge 10 ]; then
 	set -xv
 fi
 
-if [ "$check_ssh_key" -ne 0 ]; then
-	check_for_ssh_key || panic "no ssh key is available"
+if [ -n "$repo" -a ${#inputs[@]} -gt 1 ]; then
+	usage "cannot specify repository name when multiple inputs"
 fi
 
 failures=()
+
+tmp_org_name=
+tmp_repo_name=
+trap perform_cleanup EXIT
 
 for input in "${inputs[@]}"; do
 
@@ -160,6 +192,40 @@ for input in "${inputs[@]}"; do
 		perror "cannot get basename"
 		continue
 	fi
+	if [ -n "$repo" ]; then
+		repo_name="$repo"
+	fi
+
+	case "$git_proto" in
+	ssh)
+		clone_url="ssh://git@github.com/$org_name/$repo_name.git"
+		;;
+	http|https)
+		gc_username=$("$ari_gc_getcred" -k username 2> /dev/null) || \
+		  gc_username=
+		if [ -n "$gc_username" ]; then
+			clone_url="https://$gc_username@github.com/$org_name/$repo_name.git"
+		else
+			clone_url=
+		fi
+		;;
+	*)
+		panic "unexpected Git protocol";;
+	esac
+	if [ -z "$clone_url" ]; then
+		perror "cannot get clone URL"
+		continue
+	fi
+
+	failed=0
+
+	############################################################
+	# Create the Git repository
+	############################################################
+
+	# No clean up is necessary.
+	tmp_org_name=
+	tmp_repo_name=
 
 	args=()
 	args+=(-D "$debug_level")
@@ -168,40 +234,65 @@ for input in "${inputs[@]}"; do
 	if [ "$verbose" -ge 2 ]; then
 		echo "Running $ari_gc_createrepo ${args[@]}"
 	fi
-	"$ari_gc_createrepo" "${args[@]}"
-	if [ $? -ne 0 ]; then
-		failures+=("$input")
-		perror "cannot create repository"
-		continue
+	"$ari_gc_createrepo" "${args[@]}" || failed=1
+
+	# Mark repository as needing to be deleted upon failure.
+	if [ "$failed" -eq 0 ]; then
+		tmp_org_name="$org_name"
+		tmp_repo_name="$repo_name"
 	fi
 
-	clone_url="ssh://git@github.com/$org_name/$repo_name.git"
+	############################################################
+	# Populate the Git repository
+	############################################################
 
-	args=()
-	if [ "$verbose" -ge 1 ]; then
-		args+=(-v)
+	if [ "$failed" -eq 0 ]; then
+		args=()
+		if [ "$verbose" -ge 1 ]; then
+			args+=(-v)
+		fi
+		if [ "$verbose" -ge 2 ]; then
+			args+=(-v)
+		fi
+		args+=(-D "$debug_level")
+		args+=(-t "$input_type")
+		args+=("$input")
+		args+=("$clone_url")
+		if [ "$verbose" -ge 2 ]; then
+			echo "Running $ari_git_makerepo ${args[@]}"
+		fi
+		"$ari_git_makerepo" "${args[@]}" || failed=1
+		if [ "$failed" -ne 0 ]; then
+			# No clean up is necessary.
+			tmp_repo_name=
+			tmp_org_name=
+		fi
 	fi
-	args+=(-t "$input_type")
-	args+=("$input")
-	args+=("$clone_url")
-	if [ "$verbose" -ge 2 ]; then
-		echo "Running $ari_git_makerepo ${args[@]}"
-	fi
-	"$ari_git_makerepo" "${args[@]}"
-	if [ $? -ne 0 ]; then
+
+	############################################################
+	# Delete the Git repository upon failure
+	############################################################
+
+	if [ "$failed" -ne 0 -a -n "$tmp_org_name" -a -n "$tmp_repo_name" ]; then
 		failures+=("$input")
 		perror "cannot make repository"
-		#"$ari_gc_deleterepo" -D "$debug_level" -o "$org_name" "$repo_name"
-		#if [ $? -ne 0 ]; then
-		#	perror "cannot delete partially constructed repository"
-		#fi
-		continue
+		"$ari_gc_deleterepo" -D "$debug_level" -o "$org_name" "$repo_name"
+		if [ $? -ne 0 ]; then
+			perror "cannot delete partially constructed repository"
+		fi
+		# No clean up is necessary.
+		tmp_repo_name=
+		tmp_org_name=
 	fi
+
+	# No clean up is necessary.
+	tmp_org_name=
+	tmp_repo_name=
 
 done
 
 if [ "${#failures[@]}" -ne 0 ]; then
-	echo "The following inputs could not be succesfully processed:"
+	echo "The following inputs could not be successfully processed:"
 	for failure in "${failures[@]}"; do
 		echo "    $failure"
 	done
diff --git a/bin/ari_git_makerelease b/bin/ari_git_makerelease
--- a/bin/ari_git_makerelease
+++ b/bin/ari_git_makerelease
@@ -26,9 +26,17 @@
 cmd_dir=$(dirname "$0") || exit 1
 source "$cmd_dir/utilities" || exit 1
 
+perform_cleanup()
+{
+	if [ -n "$tmp_dir" -a -d "$tmp_dir" ]; then
+		rm -rf "$tmp_dir" || \
+		  echo "warning: cannot remove temporary directory $tmp_dir"
+	fi
+}
+
 perror()
 {
-	echo "ERROR: $@"
+	eecho "ERROR: $@"
 }
 
 usage()
@@ -37,10 +45,16 @@ usage()
 		echo "$@" 1>&2
 	fi
 	cat <<- EOF
+	$(basename $0)
+	Retrieves a release snapshot from Git repository.
+	This retrieves the snapshot associated with a particular commit in a Git
+	repository.
+	The snapshot can be placed in either a directory or archive file.
+
 	Usage
 	=====
 
-	$0 [options]
+	$0 [options] repo output_file
 
 	Options
 	=======
@@ -61,8 +75,7 @@ usage()
 }
 
 user_name=$(whoami) || panic "cannot determine user"
-host_name=$(hostname) || panic "cannot determine hostname"
-tmp_dir_template="/tmp/ari_git_makerelease-${user_name}@${host_name}-$$-XXXXXXXX"
+tmp_dir_template="/tmp/ari_git_makerelease-${user_name}-XXXXXXXX"
 
 ari_mktemp="$cmd_dir/ari_mktemp"
 ari_git_isempty="$cmd_dir/ari_git_isempty"
@@ -116,144 +129,98 @@ else
 	discard_stdout_stderr=stdout_stderr
 fi
 
-command_status=0
-while true; do
-
-	if [ -z "$output_type" ]; then
-		case "$output_file" in
-		*.tar.gz|*.tgz)
-			output_type=tgz;;
-		*.zip)
-			output_type=zip;;
-		*)
-			output_type=dir;;
-		esac
-	fi
-
-	# Note: should we also use -L here?
-	if [ -e "$output_file" ]; then
-		command_status=1
-		perror "output already exists $output_file"
-		break
-	fi
-
-	tmp_dir=$("$ari_mktemp" -d "$tmp_dir_template")
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot make temporary directory"
-		break
-	fi
-
-	# Clone the repository.
-	conditionally_discard_output "$discard_stdout_stderr" \
-	  git clone -q "$repo" "$tmp_dir"
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot clone repository $repo"
-		break
-	fi
-
-	# Check for an empty repository.
-	empty_repo="$(GIT_DIR="$tmp_dir/.git" \
-	  conditionally_discard_output "$discard_stderr" "$ari_git_isempty")" || \
-	  panic "check for empty repository failed"
-	if [ "$empty_repo" -ne 0 ]; then
-		command_status=1
-		perror "cannot process empty repository"
-		break
-	fi
-
-	if [ "$verify_sig" -ne 0 ]; then
-
-		# Check for the existence of the tag.
-		GIT_DIR="$tmp_dir/.git" \
-		  conditionally_discard_output "$discard_stdout_stderr" \
-		  git rev-parse -q --verify "$branch"
-		if [ $? -ne 0 ]; then
-			tag_found=0
-		else
-			tag_found=1
-		fi
-		if [ "$tag_found" -ne 0 ]; then
-			GIT_DIR="$tmp_dir/.git" \
-			  conditionally_discard_output "$discard_stdout_stderr" \
-			  git tag -v "$branch"
-			if [ $? -ne 0 ]; then
-				command_status="$EXIT_STATUS_VERIFY_TAG_FAILED"
-				perror "tag verification failure"
-				break
-			fi
-			# Output verification results in more desirable format.
-			GIT_DIR="$tmp_dir/.git" git verify-tag "$branch" 2>&1
-		else
-			command_status="$EXIT_STATUS_VERIFY_TAG_FAILED"
-			perror "tag not found"
-			break
-		fi
-		if [ "$verbose" -ge 1 ]; then
-			echo "tag verification successful"
-		fi
-	fi
-
-	# Checkout the desired branch/tag.
-	if [ -n "$branch" ]; then
-		(chdir "$tmp_dir" &&
-		  conditionally_discard_output "$discard_stdout_stderr" \
-		  git checkout "$branch")
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot checkout branch/tag $branch"
-			break
-		fi
-	fi
-
-	# Remove the Git repository directory.
-	rm -rf "$tmp_dir/.git"
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot remove git repository directory"
-		break
-	fi
-
-	case "$output_type" in
-	dir)
-		mkdir -p "$output_file"
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot make directory"
-			break
-		fi
-		tar -c -f - -C "$tmp_dir" . | tar -x -f - -C "$output_file"
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot copy files"
-			break
-		fi
-		;;
-	zip)
-		(chdir "$tmp_dir" && zip -q -r - .) > "$output_file"
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot create archive"
-			break
-		fi
-		;;
-	tgz)
-		tar -c -z -f - -C "$tmp_dir" . > "$output_file"
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot create archive"
-			break
-		fi
-		;;
+if [ -z "$output_type" ]; then
+	case "$output_file" in
+	*.tar.gz|*.tgz)
+		output_type=tgz;;
+	*.zip)
+		output_type=zip;;
+	*)
+		output_type=dir;;
 	esac
-
-	break
-
-done
-
-if [ -d "$tmp_dir" -a "$cleanup" -ne 0 ]; then
-	rm -rf "$tmp_dir"
 fi
 
-exit "$command_status"
+# Note: should we also use -L here?
+if [ -e "$output_file" ]; then
+	panic "output already exists $output_file"
+fi
+
+tmp_dir=$("$ari_mktemp" -d "$tmp_dir_template") || \
+  panic "cannot make temporary directory"
+if [ "$cleanup" -ne 0 ]; then
+	trap perform_cleanup EXIT
+fi      
+
+# Clone the repository.
+conditionally_discard_output "$discard_stdout_stderr" \
+  git clone -q "$repo" "$tmp_dir" || \
+  panic "cannot clone repository $repo"
+
+# Check for an empty repository.
+empty_repo="$(GIT_DIR="$tmp_dir/.git" \
+  conditionally_discard_output "$discard_stderr" "$ari_git_isempty")" || \
+  panic "check for empty repository failed"
+if [ "$empty_repo" -ne 0 ]; then
+	panic "cannot process empty repository"
+fi
+
+if [ "$verify_sig" -ne 0 ]; then
+
+	# Check for the existence of the tag.
+	GIT_DIR="$tmp_dir/.git" \
+	  conditionally_discard_output "$discard_stdout_stderr" \
+	  git rev-parse -q --verify "$branch"
+	if [ $? -ne 0 ]; then
+		tag_found=0
+	else
+		tag_found=1
+	fi
+	if [ "$tag_found" -ne 0 ]; then
+		GIT_DIR="$tmp_dir/.git" \
+		  conditionally_discard_output "$discard_stdout_stderr" \
+		  git tag -v "$branch"
+		if [ $? -ne 0 ]; then
+			perror "tag verification failure"
+			exit "$EXIT_STATUS_VERIFY_TAG_FAILED"
+		fi
+		# Output verification results in more desirable format.
+		GIT_DIR="$tmp_dir/.git" git verify-tag "$branch" 2>&1
+	else
+		perror "tag not found"
+		exit "$EXIT_STATUS_VERIFY_TAG_FAILED"
+	fi
+	if [ "$verbose" -ge 1 ]; then
+		echo "tag verification successful"
+	fi
+fi
+
+# Checkout the desired branch/tag.
+if [ -n "$branch" ]; then
+	(chdir "$tmp_dir" &&
+	  conditionally_discard_output "$discard_stdout_stderr" \
+	  git checkout "$branch") || \
+	  panic "cannot checkout branch/tag $branch"
+fi
+
+# Remove the Git repository directory.
+rm -rf "$tmp_dir/.git" || \
+  panic "cannot remove git repository directory"
+
+case "$output_type" in
+dir)
+	mkdir -p "$output_file" || \
+	  panic "cannot make directory"
+	tar -c -f - -C "$tmp_dir" . | tar -x -f - -C "$output_file" || \
+	  panic "cannot copy files"
+	;;
+zip)
+	(chdir "$tmp_dir" && zip -q -r - .) > "$output_file" || \
+	  panic "cannot create archive"
+	;;
+tgz)
+	tar -c -z -f - -C "$tmp_dir" . > "$output_file" || \
+	  panic "cannot create archive"
+	;;
+esac
+
+exit 0
diff --git a/bin/ari_git_makerepo b/bin/ari_git_makerepo
--- a/bin/ari_git_makerepo
+++ b/bin/ari_git_makerepo
@@ -31,12 +31,24 @@ perror()
 	echo "ERROR: $@"
 }
 
+perform_cleanup()
+{
+	if [ -n "$tmp_dir" -a -d "$tmp_dir" ]; then
+		rm -rf "$tmp_dir" || \
+		  echo "warning: cannot remove temporary directory $tmp_dir"
+	fi
+}
+
 usage()
 {
 	if [ $# -gt 0 ]; then
 		echo "$@" 1>&2
 	fi
 	cat <<- EOF
+	$(basename $0)
+	This program replaces the contents of a Git repository with some specific
+	content, which is provided in a directory or archive file.
+
 	Usage
 	=====
 
@@ -59,8 +71,7 @@ usage()
 }
 
 user_name=$(whoami) || panic "cannot determine user"
-host_name=$(hostname) || panic "cannot determine hostname"
-tmp_dir_template="${ARI_TMPDIR:-/tmp}/ari_git_makerepo-${user_name}@${host_name}-$$-XXXXXXXX"
+tmp_dir_template="${ARI_TMPDIR:-/tmp}/ari_git_makerepo-${user_name}-XXXXXXXX"
 
 ari_mktemp="$cmd_dir/ari_mktemp"
 
@@ -106,158 +117,96 @@ else
 	discard_stdout_stderr=stdout_stderr
 fi
 
-command_status=0
-while true; do
-
-	tmp_dir=$("$ari_mktemp" -d "$tmp_dir_template")
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot make temporary directory"
-		break
-	fi
-
-	if [ "$debug_level" -ge 1 ]; then
-		echo "temporary directory: $tmp_dir"
-	fi
-
-	# Determine the input type, if necessary.
-	if [ -z "$input_type" ]; then
-		if [ -d "$input" ]; then
-			input_type=dir
-		fi
-		case "$input_type" in
-		*.zip)
-			input_type=zip;;
-		*.tgz|*.tar.gz)
-			input_type=tgz;;
-		esac
-		if [ -z "$input_type" ]; then
-			command_status=1
-			perror "could not determine input type"
-			break
-		fi
-	fi
-
-	bare_dir="$tmp_dir/repo.git"
-	normal_dir="$tmp_dir/repo"
-
-	for dir in "$bare_dir" "$normal_dir"; do
-		mkdir -p "$dir"
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot make directory $dir"
-			break 2
-		fi
-	done
-
-	if [ "$verbose" -ge 2 ]; then
-		echo "Building temporary repository $bare_dir"
-	fi
-	(chdir "$bare_dir" && \
-	  conditionally_discard_output "$discard_stdout_stderr" \
-	  git init --bare .)
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot create bare repository"
-		break
-	fi
-	(chdir "$normal_dir" && \
-	  conditionally_discard_output "$discard_stdout_stderr" \
-	  git clone "$bare_dir" .)
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot clone bare repository"
-		break
-	fi
-
-	case "$input_type" in
-	dir)
-		if [ "$verbose" -ge 2 ]; then
-			ls -alR "$input"
-		fi
-		tar -C "$input" -cf - . | tar -C "$normal_dir" -xf -
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot copy files"
-			break
-		fi
-		;;
-	zip)
-		unzip -q -d "$normal_dir" "$input"
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot extract files from zip archive"
-			break
-		fi
-		;;
-	tgz)
-		tar -x -z -f "$input" -C "$normal_dir"
-		if [ $? -ne 0 ]; then
-			command_status=1
-			perror "cannot extract files from tar archive"
-			break
-		fi
-		;;
-	*)
-		panic "unknown input type"
-		;;
-	esac
-
-	(chdir "$normal_dir" && \
-	  conditionally_discard_output "$discard_stdout_stderr" \
-	  git add .)
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot add files to repository"
-		break
-	fi
-	(chdir "$normal_dir" && \
-	  conditionally_discard_output "$discard_stdout_stderr" \
-	  git commit -m "Initial commit")
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot commit changes"
-		break
-	fi
-	(chdir "$normal_dir" && \
-	  conditionally_discard_output "$discard_stdout_stderr" \
-	  git config --local push.default simple)
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot set push.default"
-		break
-	fi
-	(chdir "$normal_dir" && \
-	  conditionally_discard_output "$discard_stdout_stderr" \
-	  git push)
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot push changes"
-		break
-	fi
-
-	if [ "$verbose" -ge 2 ]; then
-		echo "Copying temporary repository to target repository $repo_url"
-	fi
-#	(chdir "$bare_dir" && \
-#	  conditionally_discard_output "$discard_stdout_stderr" \
-#	  git push --mirror "$repo_url")
-	GIT_DIR="$bare_dir" \
-	  conditionally_discard_output "$discard_stdout_stderr" \
-	  git push --mirror "$repo_url"
-	if [ $? -ne 0 ]; then
-		command_status=1
-		perror "cannot push to target repository $repo_url"
-		break
-	fi
-
-	break
-
-done
-
-if [ "$cleanup" -ne 0 -a -d "$tmp_dir" ]; then
-	rm -rf "$tmp_dir"
-	true
+tmp_dir=$("$ari_mktemp" -d "$tmp_dir_template") || \
+  panic "cannot make temporary directory"
+if [ "$cleanup" -ne 0 ]; then
+	trap perform_cleanup EXIT
 fi
 
-exit "$command_status"
+if [ "$debug_level" -ge 1 ]; then
+	echo "temporary directory: $tmp_dir"
+fi
+
+# Determine the input type, if necessary.
+if [ -z "$input_type" ]; then
+	if [ -d "$input" ]; then
+		input_type=dir
+	fi
+	case "$input_type" in
+	*.zip)
+		input_type=zip;;
+	*.tgz|*.tar.gz)
+		input_type=tgz;;
+	esac
+	if [ -z "$input_type" ]; then
+		panic "could not determine input type"
+	fi
+fi
+
+bare_dir="$tmp_dir/repo.git"
+normal_dir="$tmp_dir/repo"
+
+for dir in "$bare_dir" "$normal_dir"; do
+	mkdir -p "$dir" || \
+	  panic "cannot make directory $dir"
+done
+
+if [ "$verbose" -ge 2 ]; then
+	echo "Building temporary repository $bare_dir"
+fi
+(chdir "$bare_dir" && \
+  conditionally_discard_output "$discard_stdout_stderr" \
+  git init --bare .) || \
+  panic "cannot create bare repository"
+(chdir "$normal_dir" && \
+  conditionally_discard_output "$discard_stdout_stderr" \
+  git clone "$bare_dir" .) || \
+  panic "cannot clone bare repository"
+
+case "$input_type" in
+dir)
+	if [ "$verbose" -ge 2 ]; then
+		ls -alR "$input"
+	fi
+	tar -C "$input" -cf - . | tar -C "$normal_dir" -xf - || \
+	  panic "cannot copy files"
+	;;
+zip)
+	unzip -q -d "$normal_dir" "$input" || \
+	  panic "cannot extract files from zip archive"
+	;;
+tgz)
+	tar -x -z -f "$input" -C "$normal_dir" || \
+	  panic "cannot extract files from tar archive"
+	;;
+*)
+	panic "unknown input type"
+	;;
+esac
+
+(chdir "$normal_dir" && \
+  conditionally_discard_output "$discard_stdout_stderr" \
+  git add .) || \
+  panic "cannot add files to repository"
+(chdir "$normal_dir" && \
+  conditionally_discard_output "$discard_stdout_stderr" \
+  git commit -m "Initial commit") || \
+  panic "cannot commit changes"
+(chdir "$normal_dir" && \
+  conditionally_discard_output "$discard_stdout_stderr" \
+  git config --local push.default simple) || \
+  panic "cannot set push.default"
+(chdir "$normal_dir" && \
+  conditionally_discard_output "$discard_stdout_stderr" \
+  git push) || \
+  panic "cannot push changes"
+
+if [ "$verbose" -ge 2 ]; then
+	echo "Copying temporary repository to target repository $repo_url"
+fi
+GIT_DIR="$bare_dir" \
+  conditionally_discard_output "$discard_stdout_stderr" \
+  git push --mirror "$repo_url" || \
+  panic "cannot push to target repository $repo_url"
+
+exit 0
