Made a few small improvements to the ari_gc_dostat script (e.g., added a few new command-line options).

diff --git a/bin/ari_gc_dostat b/bin/ari_gc_dostat
--- a/bin/ari_gc_dostat
+++ b/bin/ari_gc_dostat
@@ -119,7 +119,7 @@ inter_item_sleep=10
 inter_iter_sleep=60
 git_proto="$("$ari_gc_getcred" -k gc_git_protocol)" || git_proto=https
 
-while getopts D:r:p:o:d:nRvg: option; do
+while getopts D:r:p:o:d:nRvg:y:z: option; do
 	case "$option" in
 	D)
 		debug_level="$OPTARG";;
@@ -139,6 +139,10 @@ while getopts D:r:p:o:d:nRvg: option; do
 		verbose=$((verbose + 1));;
 	g)
 		git_proto="$OPTARG";;
+	y)
+		inter_iter_sleep="$OPTARG";;
+	z)
+		inter_item_sleep="$OPTARG";;
 	*)
 		usage "invalid option $option";;
 	esac
@@ -232,11 +236,12 @@ while true; do
 		commit_id=
 		old_state=
 		state=
+		start_time="$(date +%Y-%m-%dT%H:%M)" || panic
 
 		if [ "$verbose" -ge 1 ]; then
 			cat <<- EOF
 			############################################################
-			Processing $repo_name ($((repo_index + 1))/${#repo_names[@]})
+			Processing $repo_name ($((repo_index + 1))/${#repo_names[@]}) [$start_time]
 			############################################################
 			EOF
 		fi
@@ -292,16 +297,27 @@ while true; do
 
 		# This appears to be incorrect.
 		# The git rev-parse always fails.
-		#if [ "$skip" -eq 0 ]; then
-		#	git rev-parse --verify master 2> /dev/null
-		#	if [ $? -ne 0 ]; then
-		#		eecho "warning: no master branch"
-		#		printf "ERROR: no master branch\n" > "$tmp_file" || \
-		#		  panic "printf failed"
-		#		skip=1
-		#		make_issue=1
-		#	fi
-		#fi
+		if [ "$skip" -eq 0 ]; then
+			# Note: Checking for master (as opposed to origin/master) seems
+			# not to work in all cases.  For example, it seems to fail when
+			# the master and main branches share not common ancestor.
+			(cd "$repo_dir" && \
+			  git rev-parse --verify origin/master >& /dev/null)
+			if [ $? -ne 0 ]; then
+				cat >> "$tmp_file" <<- EOF
+				Status: Error (No Branch Named "master")
+
+				The repository has no branch named "master".
+				As a submission, this would result in grade of zero.
+				EOF
+				[ $? -eq 0 ] || panic "output failed"
+				state=no_master
+				if [ "$old_state" != "$state" ]; then
+					make_issue=1
+				fi
+				skip=1
+			fi
+		fi
 
 		if [ "$skip" -eq 0 ]; then
 			(cd "$repo_dir" && git checkout -q "$branch")
@@ -315,11 +331,11 @@ while true; do
 				As a submission, this would result in grade of zero.
 				EOF
 				[ $? -eq 0 ] || panic "output failed"
-				skip=1
 				state=no_master
 				if [ "$old_state" != "$state" ]; then
 					make_issue=1
 				fi
+				skip=1
 			fi
 		fi
 
@@ -417,12 +433,12 @@ while true; do
 				As a submission, this would result in grade of zero.
 				EOF
 				[ $? -eq 0 ] || panic "output failed"
-				skip=1
 				# Note $state should be master here
 				if [ "$old_state" != "$state" -o \
 				  "$commit_id" != "$old_commit_id" ]; then
 					make_issue=1
 				fi
+				skip=1
 			fi
 		fi
 
