Removed the "-F" option from ari_precheck and changed this script to always perform full processing. Added a "-R" (reproducible) option to ari_precheck. Removed "-F" from the list of options used for ari_precheck in a few commands (i.e., ari_demo and assignment_precheck). Updated the usage information for assignment_precheck. Changed ari_validate so that student information is printed in verbose mode. Changed ari_precheck and ari_process to categorize failure types. Added a verbose option ("-v") to ari_process.

diff --git a/bin/ari_precheck b/bin/ari_precheck
--- a/bin/ari_precheck
+++ b/bin/ari_precheck
@@ -63,6 +63,8 @@ usage()
 	    Increase the verbosity level of output.
 	-f
 	    Perform the test and report-generation operations.
+	-R
+	    Enable reproducible mode (for testing).
 
 	Exit status:
 	0 all items successfully processed
@@ -87,9 +89,9 @@ in_sources=()
 in_type=
 in_subtype=
 verbose=0
-full=0
+reproducible=0
 
-while getopts FD:d:p:a:i:t:s:v option; do
+while getopts D:d:p:a:i:t:s:vR option; do
 	case "$option" in
 	D)
 		debug_level="$OPTARG";;
@@ -107,8 +109,8 @@ while getopts FD:d:p:a:i:t:s:v option; do
 		in_subtype="$OPTARG";;
 	v)
 		verbose=$((verbose + 1));;
-	F)
-		full=1;;
+	R)
+		reproducible=1;;
 	*)
 		usage "invalid option $option";;
 	esac
@@ -131,7 +133,9 @@ fi
 #	usage "no input type specified"
 #fi
 
-skipped_in_sources=()
+import_failures=()
+validate_failures=()
+all_failures=()
 
 for in_source in "${in_sources[@]}"; do
 
@@ -196,7 +200,8 @@ for in_source in "${in_sources[@]}"; do
 	"$ari_import" "${import_opts[@]}"
 	if [ $? -ne 0 ]; then
 		echo "import failed"
-		skipped_in_sources+=("$in_source")
+		import_failures+=("$in_source")
+		all_failures+=("$in_source")
 		continue
 	fi
 
@@ -211,7 +216,8 @@ for in_source in "${in_sources[@]}"; do
 
 	if [ "$validate_status" -ne 0 ]; then
 		eecho "THIS ASSIGNMENT WILL RECEIVE A MARK OF ZERO IF SUBMITTED!"
-		skipped_in_sources+=("$in_source")
+		validate_failures+=("$in_source")
+		all_failures+=("$in_source")
 		warn "skipping remainder of processing for input $in_source"
 		continue
 	fi
@@ -223,7 +229,7 @@ for in_source in "${in_sources[@]}"; do
 	"$ari_generate" "${generate_opts[@]}"
 	if [ $? -ne 0 ]; then
 		echo "generation failed"
-		skipped_in_sources+=("$in_source")
+		all_failures+=("$in_source")
 		continue
 	fi
 
@@ -231,47 +237,53 @@ for in_source in "${in_sources[@]}"; do
 	build_opts+=(-D "$debug_level")
 	build_opts+=(-d "$project_dir")
 	build_opts+=(-O)
+	if [ "$reproducible" -ne 0 ]; then
+		report_args+=(-R)
+	fi
 	if [ "$verbose" -ge 1 ]; then
 		build_opts+=(-v)
 	fi
 	"$ari_build" "${build_opts[@]}"
 	if [ $? -ne 0 ]; then
 		echo "build failed"
-		skipped_in_sources+=("$in_source")
+		all_failures+=("$in_source")
 		continue
 	fi
 
-	if [ "$full" -ne 0 ]; then
 
-		test_opts=()
-		test_opts+=(-D "$debug_level")
-		test_opts+=(-d "$project_dir")
-		test_opts+=(-O)
-		if [ "$verbose" -ge 1 ]; then
-			test_opts+=(-v)
-		fi
-		"$ari_test" "${test_opts[@]}"
-		if [ $? -ne 0 ]; then
-			echo "test failed"
-			skipped_in_sources+=("$in_source")
-			continue
-		fi
+	test_opts=()
+	test_opts+=(-D "$debug_level")
+	test_opts+=(-d "$project_dir")
+	test_opts+=(-O)
+	if [ "$reproducible" -ne 0 ]; then
+		report_args+=(-R)
+	fi
+	if [ "$verbose" -ge 1 ]; then
+		test_opts+=(-v)
+	fi
+	"$ari_test" "${test_opts[@]}"
+	if [ $? -ne 0 ]; then
+		echo "test failed"
+		all_failures+=("$in_source")
+		continue
+	fi
 
-		report_opts=()
-		report_opts+=(-D "$debug_level")
-		report_opts+=(-d "$project_dir")
-		report_opts+=(-o "$project_dir/report.pdf")
-		report_opts+=(-O)
-		#if [ "$verbose" -ge 1 ]; then
-		#	report_opts+=(-v)
-		#fi
-		"$ari_report" "${report_opts[@]}"
-		if [ $? -ne 0 ]; then
-			echo "test failed"
-			skipped_in_sources+=("$in_source")
-			continue
-		fi
-
+	report_opts=()
+	report_opts+=(-D "$debug_level")
+	report_opts+=(-d "$project_dir")
+	report_opts+=(-o "$project_dir/report.pdf")
+	report_opts+=(-O)
+	if [ "$reproducible" -ne 0 ]; then
+		report_args+=(-R)
+	fi
+	#if [ "$verbose" -ge 1 ]; then
+	#	report_opts+=(-v)
+	#fi
+	"$ari_report" "${report_opts[@]}"
+	if [ $? -ne 0 ]; then
+		echo "report failed"
+		all_failures+=("$in_source")
+		continue
 	fi
 
 done
@@ -282,14 +294,24 @@ if [ "${#in_sources[@]}" -gt 1 ]; then
 	Summary
 	############################################################
 	EOF
-	echo "Number of skipped items: ${#skipped_in_sources[@]}"
-	echo "Skipped items:"
-	for in_source in "${skipped_in_sources[@]}"; do
+	echo "Number of import failures: ${#import_failures[@]}"
+	echo "Import failures:"
+	for in_source in "${import_failures[@]}"; do
+		echo "$in_source"
+	done
+	echo "Number of validation failures: ${#validate_failures[@]}"
+	echo "Validation failures:"
+	for in_source in "${validate_failures[@]}"; do
+		echo "$in_source"
+	done
+	echo "Total number of failures: ${#all_failures[@]}"
+	echo "All failures:"
+	for in_source in "${all_failures[@]}"; do
 		echo "$in_source"
 	done
 fi
 
-if [ ${#skipped_in_sources[@]} -gt 0 ]; then
+if [ ${#all_failures[@]} -gt 0 ]; then
 	fatal_error 1 "one or more items could not be succesfully processed"
 fi
 
diff --git a/bin/ari_process b/bin/ari_process
--- a/bin/ari_process
+++ b/bin/ari_process
@@ -43,6 +43,8 @@ usage()
 	    Skip optional items.
 	-R
 	    Enable reproducible mode (for testing).
+	-v
+	    Increase verbosity level of output.
 	EOF
 	exit 2
 }
@@ -57,8 +59,9 @@ ari_info="$cmd_dir/ari_info"
 reproducible=0
 skip_optional=0
 debug_level=${ARI_DEBUG_LEVEL:-0}
+verbose=0
 
-while getopts ROD:o: option; do
+while getopts ROD:o:v option; do
 	case "$option" in
 	R)
 		reproducible=1;;
@@ -66,13 +69,16 @@ while getopts ROD:o: option; do
 		skip_optional=1;;
 	D)
 		debug_level="$OPTARG";;
+	v)
+		verbose=$((verbose + 1));;
 	*)
 		usage "invalid option $option";;
 	esac
 done
 shift $((OPTIND - 1))
 
-skipped_dirs=()
+validate_failures=()
+all_failures=()
 dirs=("$@")
 
 for dir in "${dirs[@]}"; do
@@ -94,6 +100,9 @@ for dir in "${dirs[@]}"; do
 	validate_args=()
 	validate_args+=(-D "$debug_level")
 	validate_args+=(-d "$project_dir")
+	if [ "$verbose" -ge 1 ]; then
+		validate_opts+=(-v)
+	fi
 	if [ "$debug_level" -ge 1 ]; then
 		eecho "Running ari_validate ${validate_args[@]}"
 	fi
@@ -101,9 +110,11 @@ for dir in "${dirs[@]}"; do
 	validate_status=$?
 
 	if [ "$validate_status" -ne 0 ]; then
-		warn "validation failed for $dir"
-		warn "skipping $dir"
-		skipped_dirs+=("$dir")
+		eecho "THIS ASSIGNMENT WILL RECEIVE A MARK OF ZERO IF SUBMITTED!"
+		warn "validation failed for input $dir"
+		warn "skipping remainder of processing for input $dir"
+		validate_failures+=("$dir")
+		all_failures+=("$dir")
 		continue
 	fi
 
@@ -131,15 +142,21 @@ for dir in "${dirs[@]}"; do
 	if [ "$debug_level" -ge 1 ]; then
 		eecho "Running ari_generate ${generate_args[@]}"
 	fi
-	"$ari_generate" "${generate_args[@]}" || \
-	  panic "generation failed"
+	"$ari_generate" "${generate_args[@]}"
+	if [ $? -ne 0 ]; then
+		echo "generation failed"
+		all_failures+=("$dir")
+		continue
+	fi
 
 	############################################################
 	# Build the packages for the assignment.
 	############################################################
 
 	build_args=()
-	build_args+=(-v)
+	if [ "$verbose" -ge 1 ]; then
+		build_args+=(-v)
+	fi
 	build_args+=(-D "$debug_level")
 	build_args+=(-d "$project_dir")
 	build_args+=(-c)
@@ -149,12 +166,15 @@ for dir in "${dirs[@]}"; do
 	if [ "$skip_optional" -ne 0 ]; then
 		build_args+=(-O)
 	fi
-	###build_args+=(-u)
 	if [ "$debug_level" -ge 1 ]; then
 		eecho "Running ari_build ${build_args[@]}"
 	fi
-	"$ari_build" "${build_args[@]}" || \
-	  panic "build failed"
+	"$ari_build" "${build_args[@]}"
+	if [ $? -ne 0 ]; then
+		echo "build failed"
+		all_failures+=("$dir")
+		continue
+	fi
 
 	############################################################
 	# Test the packages for the assignment.
@@ -164,18 +184,23 @@ for dir in "${dirs[@]}"; do
 	if [ "$skip_optional" -ne 0 ]; then
 		test_args+=(-O)
 	fi
-	test_args+=(-v)
+	if [ "$verbose" -ge 1 ]; then
+		test_args+=(-v)
+	fi
 	test_args+=(-D "$debug_level")
 	test_args+=(-d "$project_dir")
-	#test_args+=(-u)
 	if [ "$reproducible" -ne 0 ]; then
 		test_args+=(-R)
 	fi
 	if [ "$debug_level" -ge 1 ]; then
 		eecho "Testing"
 	fi
-	"$ari_test" "${test_args[@]}" || \
-	  panic "test failed"
+	"$ari_test" "${test_args[@]}"
+	if [ $? -ne 0 ]; then
+		echo "test failed"
+		all_failures+=("$dir")
+		continue
+	fi
 
 	############################################################
 	# Generate the report for the assignment.
@@ -188,15 +213,21 @@ for dir in "${dirs[@]}"; do
 	report_args+=(-D "$debug_level")
 	report_args+=(-d "$project_dir")
 	report_args+=(-o "$project_dir/report.pdf")
-	#report_args+=(-u)
 	if [ "$reproducible" -ne 0 ]; then
 		report_args+=(-R)
 	fi
 	if [ "$debug_level" -ge 1 ]; then
 		eecho "Reporting"
 	fi
-	"$ari_report" "${report_args[@]}" || \
-	  panic "report failed"
+	#if [ "$verbose" -ge 1 ]; then
+	#	report_args+=(-v)
+	#fi
+	"$ari_report" "${report_args[@]}"
+	if [ $? -ne 0 ]; then
+		echo "report failed"
+		all_failures+=("$dir")
+		continue
+	fi
 
 	alt_report_file="$project_dir/report-$project-$section-$mangled_student_name-$student_id.pdf"
 	if [ -L "$alt_report_file" -o -e "$alt_report_file" ]; then
@@ -213,10 +244,17 @@ if [ "${#dirs[@]}" -gt 1 ]; then
 	Summary
 	############################################################
 	EOF
-	echo "Number of skipped items: ${#skipped_dirs[@]}"
-	if [ ${#skipped_dirs[@]} -gt 0 ]; then
-		echo "Skipped items:"
-		for dir in "${skipped_dirs[@]}"; do
+	echo "Number of validation failures: ${#validate_failures[@]}"
+	if [ ${#validate_failures[@]} -gt 0 ]; then
+		echo "Validation failures:"
+		for dir in "${validate_failures[@]}"; do
+			echo "$dir"
+		done
+	fi
+	echo "Total number of failures: ${#all_failures[@]}"
+	if [ ${#all_failures[@]} -gt 0 ]; then
+		echo "All failures:"
+		for dir in "${all_failures[@]}"; do
 			echo "$dir"
 		done
 	fi
