Changed the ari_run_catch_app script to allow each test case to be run in a separate invocation of the Catch2 test application.

diff --git a/bin/ari_run_catch_app b/bin/ari_run_catch_app
--- a/bin/ari_run_catch_app
+++ b/bin/ari_run_catch_app
@@ -48,8 +48,8 @@ usage()
 	exit status:
 	0 ... Catch2 application ran to completion and all tests passed
 	1 ... Catch2 application ran to completion but some tests failed
-	2 ... Catch2 application did not run to completion but exited gracefully
-	3 ... Catch2 application did not run to completion and died violently
+	2 ... Catch2 application did not run to completion but summary generated
+	3 ... Catch2 application did not run to completion and no summary generated
 	4 ... other fatal error
 	5 ... bad usage
 	EOF
@@ -65,21 +65,27 @@ ari_timeout="$cmd_dir/ari_timeout"
 user="$whoami"
 host=$(hostname)
 tmp_dir=/tmp/ari_run_catch_app-$user@$host-$$
-console_file="$tmp_dir/console_file"
-xml_file="$tmp_dir/xml_file"
+console_file="$tmp_dir/console"
+log_file="$tmp_dir/log"
 debug_level=${ARI_DEBUG_LEVEL:-0}
+tests_file="$tmp_dir/tests"
 
 ################################################################################
 #
 ################################################################################
 
 command=
+run_individually=0
 result=0
 result_file="$ARI_TEST_RESULT_FILE"
 timeout=
 
-while getopts D:c:rt:f: opt; do
+while getopts AID:c:rt:f: opt; do
 	case $opt in
+	A)
+		run_individually=0;;
+	I)
+		run_individually=1;;
 	c)
 		command="$OPTARG";;
 	t)
@@ -107,6 +113,10 @@ if [ -z "$command" ]; then
 	panic "no command specified"
 fi
 
+if [ "$debug_level" -ge 100 ]; then
+	set -xv
+fi
+
 ################################################################################
 #
 ################################################################################
@@ -124,125 +134,224 @@ echo "$buffer" | grep -q -e '[0-9]\+.\+test cases' || \
   panic "invalid output generated by Catch2 application"
 num_tests=$(echo "$buffer" | get_nth_word 1) || \
   panic "cannot extract number of test cases"
-if [ "$num_tests" -ge 128 ]; then
-	eecho "since more than 127 test cases, cannot rely on Catch2 app exit status"
+
+# Obtain a list of the tests.
+# Catch2 sets the exit status to the number of test cases clamped at 255.
+# Due to this braindamage, we cannot rely on the exit status to know if
+# this list of tests was successfully output.
+# So, we simply check if the number of tests listed matches the number
+# of tests obtained from the query above.
+"$command" --list-test-names-only > "$tests_file"
+mapfile -t all_tests < "$tests_file" || \
+  panic "cannot read tests file"
+if [ "${#all_tests[@]}" -ne "$num_tests" ]; then
+	panic "cannot get tests"
 fi
 
-# Run the test application.
-if [ -n "$timeout" ]; then
-	# Run the test application with a timeout.
-	"$ari_timeout" -t "$timeout" -k 10 "$command" -r console \
-	  > "$console_file" 2> /dev/null
-	app_exit_status=$?
+if [ "$debug_level" -ge 1 ]; then
+	for test in "${all_tests[@]}"; do
+		echo "$test"
+	done
+fi
+
+tests=("${all_tests[@]}")
+cum_total_tests=0
+cum_failed_tests=0
+cum_passed_tests=0
+cum_total_assertions=0
+cum_failed_assertions=0
+cum_passed_assertions=0
+cum_missing_summaries=0
+num_runs=0
+
+if [ "$run_individually" -ne 0 ]; then
+	tests=("${all_tests[@]}")
 else
-	# Run the test application without a timeout.
-	"$command" -r console > "$console_file" 2> /dev/null
-	app_exit_status=$?
+	tests=("__all_tests__")
 fi
 
-completed=0
-has_summary=0
-if [ "$app_exit_status" -ne 0 ]; then
+for test in "${tests[@]}"; do
 
-	# Extract the summary of the test results.
-	# If any tests fail, the output should resemble:
-	# test cases:  6 |  5 passed | 1 failed
-	# assertions: 84 | 80 passed | 4 failed
-	# [blank line]
-	test_cases_buffer=$(get_nth_last_line 3 "$console_file") || \
-	  panic "cannot get test cases summary line"
-	assertions_buffer=$(get_nth_last_line 2 "$console_file") || \
-	  panic "cannot get assertions summary line"
-	has_summary=1
-	echo "$test_cases_buffer" | grep -q \
-	  -e '^test cases:[[:space:]]\+[0-9]*[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+passed[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+failed$' || \
-	  has_summary=0
-	echo "$assertions_buffer" | grep -q \
-	  -e '^assertions:[[:space:]]\+[0-9]*[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+passed[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+failed$' || \
-	  has_summary=0
+	if [ "$test" = "__all_tests__" ]; then
+		app_args=()
+	else
+		app_args=()
+		app_args+=("$test")
+	fi
 
-	if [ "$has_summary" -ne 0 ]; then
-		total_tests=$(echo "$test_cases_buffer" | get_nth_word 3) || \
-		  panic "cannot get total tests"
-		passed_tests=$(echo "$test_cases_buffer" | get_nth_word 5) || \
-		  panic "cannot get passed tests"
-		failed_tests=$(echo "$test_cases_buffer" | get_nth_word 8) || \
-		  panic "cannot get failed tests"
-		total_assertions=$(echo "$assertions_buffer" | get_nth_word 2) || \
-		  panic "cannot get total assertions"
-		passed_assertions=$(echo "$assertions_buffer" | get_nth_word 4) || \
-		  panic "cannot get passed assertions"
-		failed_assertions=$(echo "$assertions_buffer" | get_nth_word 7) || \
-		  panic "cannot get failed assertions"
-		if [ "$total_tests" -eq "$num_tests" ]; then
+	if [ -e "$console_file" ]; then
+		rm -f "$console_file" || panic "cannot remove file $console_file"
+	fi
+
+	# Run the test application.
+	if [ -n "$timeout" ]; then
+		# Run the test application with a timeout.
+		args=(-t "$timeout" -k 10 "$command" -r console "${app_args[@]}")
+		#echo "Running $ari_timeout ${args[@]}"
+		"$ari_timeout" "${args[@]}" > "$console_file" 2> /dev/null
+		app_exit_status=$?
+	else
+		# Run the test application without a timeout.
+		args=(-r console "${app_args[@]}")
+		#echo "Running $command ${args[@]}"
+		"$command" "${args[@]}" > "$console_file" 2> /dev/null
+		app_exit_status=$?
+	fi
+	num_runs=$((num_runs + 1))
+
+	if [ "$app_exit_status" -ne 0 ]; then
+
+		# Extract the summary of the test results.
+		# If any tests fail, the output should resemble:
+		# test cases:  6 |  5 passed | 1 failed
+		# assertions: 84 | 80 passed | 4 failed
+		# [blank line]
+		tests_buffer=$(get_nth_last_line 3 "$console_file") || \
+		  panic "cannot get test cases summary line"
+		assertions_buffer=$(get_nth_last_line 2 "$console_file") || \
+		  panic "cannot get assertions summary line"
+		if [ "$debug_level" -ge 1 ]; then
+			eecho "$tests_buffer"
+			eecho "$assertions_buffer"
+		fi
+		has_summary=1
+		echo "$tests_buffer" | grep -q \
+		  -e '^test cases:[[:space:]]\+[0-9]*[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+passed[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+failed$' || \
+		  has_summary=0
+		echo "$assertions_buffer" | grep -q \
+		  -e '^assertions:[[:space:]]\+[0-9]*[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+passed[[:space:]]\+|[[:space:]]\+[0-9]*[[:space:]]\+failed$' || \
+		  has_summary=0
+
+		if [ "$has_summary" -ne 0 ]; then
+			total_tests=$(echo "$tests_buffer" | get_nth_word 3) || \
+			  panic "cannot get total tests"
+			passed_tests=$(echo "$tests_buffer" | get_nth_word 5) || \
+			  panic "cannot get passed tests"
+			failed_tests=$(echo "$tests_buffer" | get_nth_word 8) || \
+			  panic "cannot get failed tests"
+			total_assertions=$(echo "$assertions_buffer" | get_nth_word 2) || \
+			  panic "cannot get total assertions"
+			passed_assertions=$(echo "$assertions_buffer" | get_nth_word 4) || \
+			  panic "cannot get passed assertions"
+			failed_assertions=$(echo "$assertions_buffer" | get_nth_word 7) || \
+			  panic "cannot get failed assertions"
 			completed=1
 		else
 			completed=0
 		fi
 	else
-		completed=0
 
-		# Re-run the test application reporting successful tests.
-		if [ -n "$timeout" ]; then
-			# Run the test application with a timeout.
-			"$ari_timeout" -t "$timeout" -k 10 "$command" -r xml -s \
-			  > "$xml_file" 2> /dev/null
-			alt_app_exit_status=$?
-		else
-			# Run the test application without a timeout.
-			"$command" -r xml -s > "$xml_file" 2> /dev/null
-			alt_app_exit_status=$?
+		# If all tests pass, then the output should resemble:
+		# All tests passed (723 assertions in 22 test cases)
+		# [blank line]
+		buffer=$(get_nth_last_line 2 "$console_file") || \
+		  panic "cannot get status line"
+		if [ "$debug_level" -ge 1 ]; then
+			eecho "$buffer"
 		fi
-		eecho "fallback app exit status $alt_app_exit_status"
+		has_summary=1
+		echo "$buffer" | \
+		  grep -q \
+		  -E '^All tests passed \([0-9]*[[:space:]]+assertions in[[:space:]]+[0-9]*[[:space:]]+test (cases|case)\)$' || \
+		  has_summary=0
+		if [ "$has_summary" -ne 0 ]; then
+			buffer=$(echo "$buffer" | tr '()' '  ')
+			total_assertions=$(echo "$buffer" | get_nth_word 4) || \
+			  panic "cannot get total assertions"
+			total_tests=$(echo "$buffer" | get_nth_word 7) || \
+			  panic "cannot get total tests"
+			passed_tests="$total_tests"
+			passed_assertions="$total_assertions"
+			failed_tests=0
+			failed_assertions=0
+		else
+			panic "cannot parse summary of test results"
+		fi
 
-		# Extract the number of test cases run.
-		total_tests=$(cat "$xml_file" | grep -e '<TestCase.*>' | wc -l) || \
-		  panic "cannot extract number of test cases"
-		total_tests="$total_tests"
-
-		# Extract the number of assertions tested.
-		total_assertions=$(cat "$xml_file" | grep -e '<Expression.*>' | \
-		  wc -l) || \
-		  panic "cannot extract number of assertions"
-		total_assertions="$total_assertions"
-
-		passed_tests=""
-		failed_tests=""
-		passed_assertions=""
-		failed_assertions=""
+		completed=1
 	fi
 
-	if [ "$completed" -eq 1 ]; then
-		result_message="COM,$failed_assertions/$total_assertions,$failed_tests/$total_tests"
+	if [ "$has_summary" -ne 0 ]; then
+		cum_total_tests=$((cum_total_tests + total_tests))
+		cum_passed_tests=$((cum_passed_tests + passed_tests))
+		cum_failed_tests=$((cum_failed_tests + failed_tests))
+		cum_total_assertions=$((cum_total_assertions + total_assertions))
+		cum_passed_assertions=$((cum_passed_assertions + passed_assertions))
+		cum_failed_assertions=$((cum_failed_assertions + failed_assertions))
 	else
-		if [ "$has_summary" -ne 0 ]; then
-			result_message="INC,$failed_assertions/$total_assertions,$failed_tests/$total_tests"
+		cum_missing_summaries=$((cum_missing_summaries + 1))
+	fi
+
+	if [ "$debug_level" -ge 1 ]; then
+		eecho "completed: $completed"
+		eecho "has summary: $has_summary"
+		eecho "total tests: $total_tests"
+		eecho "passed tests: $passed_tests"
+		eecho "failed tests: $failed_tests"
+		eecho "total assertions: $total_assertions"
+		eecho "passed assertions: $passed_assertions"
+		eecho "failed assertions: $failed_assertions"
+	fi
+
+	if [ "$app_exit_status" -ne 0 ]; then
+		cat <<- EOF
+		============================================================
+		Test Name: $test
+		============================================================
+		EOF
+		[ $? -eq 0 ] || panic "output failed"
+	fi
+
+	if [ "$has_summary" -eq 0 ]; then
+		cat <<- EOF
+		WARNING:
+		The Catch2 test application was violently terminated before
+		generating the summary of the test results.
+		The most likely cause is that the code being tested trashed
+		the stack (e.g., stack overflow or stack corruption).
+
+		EOF
+		[ $? -eq 0 ] || panic "output failed"
+	fi
+
+	if [ "$app_exit_status" -ne 0 ]; then
+		cat "$console_file" || panic "cannot copy log file"
+	fi
+
+done
+
+if [ "$debug_level" -ge 1 ]; then
+	eecho "total tests: $cum_total_tests"
+	eecho "passed tests: $cum_passed_tests"
+	eecho "failed tests: $cum_failed_tests"
+	eecho "total assertions: $cum_total_assertions"
+	eecho "passed assertions: $cum_passed_assertions"
+	eecho "failed assertions: $cum_failed_assertions"
+fi
+
+failed_tests_message="$cum_failed_tests/$cum_total_tests"
+failed_assertions_message="$cum_failed_assertions/$cum_total_assertions"
+missing_summaries_message="$cum_missing_summaries/$num_runs"
+if [ "$cum_failed_tests" -ne 0 ]; then
+	if [ "$cum_missing_summaries" -gt 0 ]; then
+		if [ "$cum_missing_summaries" -ge "$run_runs" ]; then
+			result_message="INC,($cum_failed_tests+$cum_missing_summaries)/$cum_total_tests,$cum_failed_assertions/$cum_total_assertions"
+			status_message="FAIL (NO SUMMARY)"
+			exit_status=3
 		else
-			result_message="INC,?/${total_assertions}?,?/${total_tests}?"
+			result_message="INC,($cum_failed_tests+$cum_missing_summaries)/$cum_total_tests,$cum_failed_assertions/$cum_total_assertions"
+			status_message="FAIL (INCOMPLETE SUMMARY)"
+			exit_status=2
 		fi
+	else
+		result_message="COM,$cum_failed_tests/$cum_total_tests,$cum_failed_assertions/$cum_total_assertions"
+		status_message="FAIL (COMPLETE SUMMARY)"
+		exit_status=1
 	fi
 else
-	completed=1
-
-	# If all tests pass, then the output should resemble:
-	# All tests passed (723 assertions in 22 test cases)
-	# [blank line]
-	buffer=$(get_nth_last_line 2 "$console_file") || \
-	  panic "cannot get status line"
-	has_summary=1
-	echo "$buffer" | grep -q \
-	  -e '^All tests passed ([0-9]*[[:space:]]\+assertions in[[:space:]]\+[0-9]*[[:space:]]\+test cases)$' || \
-	  has_summary=0
-	if [ "$has_summary" -ne 0 ]; then
-		buffer=$(echo "$buffer" | tr '()' '  ')
-		total_assertions=$(echo "$buffer" | get_nth_word 4) || \
-		  panic "cannot get total assertions"
-		total_tests=$(echo "$buffer" | get_nth_word 7) || \
-		  panic "cannot get total tests"
-		result_message="PASS,0/$total_assertions,0/$total_tests"
-	else
-		panic "cannot parse summary of test results"
-	fi
+	result_message="PASS,0/$cum_total_tests,0/$cum_total_assertions"
+	status_message="PASS"
+	exit_status=0
 fi
 
 if [ "$result" -ne 0 ]; then
@@ -250,67 +359,15 @@ if [ "$result" -ne 0 ]; then
 	  panic "cannot create result file"
 fi
 
-if [ "$debug_level" -ge 1 ]; then
-	eecho "completed: $completed"
-	eecho "has summary: $has_summary"
-	eecho "number of tests: $num_tests"
-	eecho "total tests: $total_tests"
-	eecho "passed tests: $passed_tests"
-	eecho "failed tests: $failed_tests"
-	eecho "total assertions: $total_assertions"
-	eecho "passed assertions: $passed_assertions"
-	eecho "failed assertions: $failed_assertions"
-fi
-
 ################################################################################
 #
 ################################################################################
 
-if [ "$completed" -ne 0 ]; then
-	if [ "$app_exit_status" -eq 0 ]; then
-		status_message="PASS"
-		failed_assertions_message="0/$total_assertions"
-		failed_tests_message="0/$total_tests"
-		exit_status=0
-	else
-		status_message="FAIL (COMPLETE WITH SUMMARY)"
-		failed_assertions_message="$failed_assertions/$total_assertions"
-		failed_tests_message="$failed_tests/$total_tests"
-		exit_status=1
-	fi
-else
-	if [ "$has_summary" -ne 0 ]; then
-		status_message="FAIL (INCOMPLETE WITH SUMMARY)"
-		failed_assertions_message="$failed_assertions/$total_assertions"
-		failed_tests_message="$failed_tests/$total_tests"
-		exit_status=2
-	else
-		status_message="FAIL (INCOMPLETE WITHOUT SUMMARY)"
-		failed_assertions_message="?/${total_assertions}?"
-		failed_tests_message="?/${total_tests}?"
-		exit_status=3
-	fi
-fi
+#echo "$result_message"
 
 ################################################################################
 #
 ################################################################################
-
-if [ "$has_summary" -eq 0 ]; then
-	cat <<- EOF
-	============================================================
-	WARNING:
-	The Catch2 test application was violently terminated before
-	generating the summary of the test results.
-	The most likely cause is that the code being tested trashed
-	the stack (e.g., stack overflow or stack corruption).
-	============================================================
-
-	EOF
-	[ $? -eq 0 ] || panic "output failed"
-fi
-
-cat "$console_file" || panic "cannot copy log file"
 
 cat <<- EOF
 
@@ -323,31 +380,43 @@ PASS
 The Catch2 test application was able to run the full set of test cases and
 all of the test cases passed.
 
-FAIL (COMPLETE WITH SUMMARY)
+FAIL (COMPLETE SUMMARY)
 The Catch2 test application was able to run the full set of test cases but
 some test cases failed.
+In some cases, the Catch2 test application may have been forced to exit
+slightly early, but the application was still able to generate a summary of
+the test results before exiting.
 
-FAIL (INCOMPLETE WITH SUMMARY)
-The Catch2 test application was forced to exit before processing the full
-set of test cases.  The application was able to generate the test-results
-summary before exiting.  This situation is typically caused by a signal being
-generated by the code being tested (such as a floating-point exception or
-segmentation fault) that does not prevent the test application from exiting
-gracefully (i.e., after having printed the test-results summary).
+FAIL (INCOMPLETE SUMMARY)
+Some (but not all) of the times that the Catch2 test application was run,
+the application was terminated before being able to generate a summary
+of the test results.
 
-FAIL (INCOMPLETE WITHOUT SUMMARY)
-The Catch2 test application was violently terminated before generating
-the test-results summary.  This is most likely caused by the code being
+FAIL (NO SUMMARY)
+Every time that the Catch2 test application was run, the application was
+terminated before being able to generate a summary of the test results.
+In this case, most test results are likely to be uknown.
+
+Note:
+If the Catch2 test application was forced to exit before processing all
+of the test cases to be run, this is typically caused by a signal being
+generated by the code being tested (such as a floating-point exception
+or segmentation fault) that does not prevent the test application from
+exiting gracefully (i.e., after having printed the summary of the test
+results).
+
+Note:
+If the Catch2 test application terminates before being able to generate
+a summary of the test results, this is likely due to the code being
 tested trashing the stack (e.g., stack overflow or stack corruption).
-In this case, the number of test cases and number of assertions actually
-tested cannot be determined reliably.  The numbers provided are an estimate.
 
 SUMMARY OF TEST RESULTS
 =======================
 
 Status: $status_message
-Failed assertions: $failed_assertions_message
 Failed tests: $failed_tests_message
+Failed assertions: $failed_assertions_message
+Missing summaries: $missing_summaries_message
 EOF
 [ $? -eq 0 ] || panic "output failed"
 
@@ -355,8 +424,8 @@ EOF
 # Cleanup
 ################################################################################
 
+rm -f "$tests_file"
 rm -f "$console_file"
-rm -f "$xml_file"
 rmdir "$tmp_dir"
 
 ################################################################################
