Added the ability to more flexibly handle failed generate operations in workspaces. Made numerous changes to the behavior of the ari_dostat script in order to make it more useful. Added a force option to the ari_gc_logout script, which forces the removal of credential-related files. Added a create_or_replace command to the ari_pkgtrans script. Added state to the workspace so that it is possible to tell if the workspace has been (successfully) validated. Unified the formatting of the help information for the various shell scripts. Added a missing usage function to several shell scripts.

diff --git a/bin/ari_dostat b/bin/ari_dostat
--- a/bin/ari_dostat
+++ b/bin/ari_dostat
@@ -45,14 +45,15 @@ print_status()
 		operation="$2"
 		target="$3"
 		status="$4"
-#		case "$status" in
-#		0|1)
-#			status="COM or OK";;
-#		3)
-#			status="INC";;
-#		*)
-#			status="UNK";;
-#		esac
+		if [ -n "$status" ]; then
+			if [ "$status" -eq 0 ]; then
+				status="OK"
+			else
+				status="FAIL"
+			fi
+		else
+			status="UNKNOWN"
+		fi
 	else
 		package="Package"
 		operation="Operation"
@@ -65,24 +66,41 @@ print_status()
 
 usage()
 {
-	echo "$@"
+	if [ $# -gt 0 ]; then
+		echo "$@" 1>&2
+	fi
 	cat <<- EOF
-	usage:
+	Usage
+	=====
+
 	$0 [options]
 
-	options:
-	-d \$work_dir
-	-r \$repo_regex
-	-o \$organization
+	Options
+	=======
 
-	examples:
+	-d \$work_dir
+	    Set the workspace directory to \$work_dir.
+	-r \$repo_regex
+	    Set the repository regular expression to \$repo_regex.
+	-p \$package_regex
+	    Set the package regular expression to \$package_regex.
+	-o \$organization
+	    Set the GitHub organization to \$organization.
+	-n
+	    Disable the creation of issues.
+	-D \$debug_level
+	    Set the debug level to \$debug_level.
+
+	Examples
+	========
+
 	$0 -d dostat -o uvic-seng475 -r 'tools-.*'
 	EOF
 	exit 2
 }
 
-cmd_dir=$(dirname "$0") || panic "cannot get command directory"
-cmd_dir=$(realpath "$cmd_dir") || panic
+cmd_dir=$(dirname "$0") || panic "cannot get program directory"
+cmd_dir=$(realpath "$cmd_dir") || panic "cannot get real path of program"
 ari_hub="$cmd_dir/ari_hub"
 ari_info="$cmd_dir/ari_info"
 
@@ -127,9 +145,11 @@ if [ -z "$package_regex" ]; then
 	usage "no packages specified"
 fi
 
-work_dir=$(realpath "$work_dir") || panic
+work_dir=$(realpath "$work_dir") || \
+  panic "cannot get real path of workspace directory"
+tmp_dir="$work_dir/tmp"
 
-for dir in "$work_dir"; do
+for dir in "$work_dir" "$tmp_dir"; do
 	if [ ! -d "$dir" ]; then
 		mkdir -p "$dir" || panic "cannot make directory"
 	fi
@@ -164,11 +184,13 @@ while true; do
 		#repo_url="https://github.com/$organization/$repo_name.git"
 		item_dir="$work_dir/$repo_name"
 		old_commit_id_file="$item_dir/commit_id"
-		workspace_dir="$item_dir/workspace"
+		old_workspace_dir="$item_dir/workspace"
+		workspace_dir="$item_dir/tmp_workspace"
 		repo_dir="$item_dir/repository"
 		commit_id_file="$workspace_dir/commit_id"
+		validate_status_file="$workspace_dir/validate/status"
 		issue_dir="$item_dir/issues"
-		tmp_file="$workspace_dir/tmp_file"
+		tmp_file="$tmp_dir/hub_issue"
 		time="$(date +%Y-%m-%d-%H-%M-%S)" || panic "cannot get time"
 		issue_file="$issue_dir/issue-$time"
 
@@ -224,7 +246,8 @@ while true; do
 
 		if [ "$skip" -eq 0 ]; then
 
-			project="$(cat "$workspace_dir/assignment_id")" || panic
+			project="$(cat "$workspace_dir/assignment_id")" || \
+			  panic "cannot get assignment ID"
 
 			if [ -f "$old_commit_id_file" ]; then
 				old_commit_id="$(cat "$old_commit_id_file")" || \
@@ -249,17 +272,30 @@ while true; do
 
 		fi
 
+		printf "" > "$tmp_file" || panic "cannot create temporary file"
+		printf "%s\n\n" "Status: Commit $commit_id" >> "$tmp_file" || \
+		  panic "cannot append to temporary file"
+		printf "Commit ID: $commit_id\n" >> "$tmp_file" || \
+		  panic "cannot append to temporary file"
+
 		if [ "$skip" -eq 0 ]; then
 
 			ari_process -v "$workspace_dir"
 			status=$?
 
-			packages=($("$ari_info" -a "$project" packages)) || \
-			  panic "cannot get package list"
-
-			#packages=($((cd "$workspace_dir" && \
-			#  find . -mindepth 1 -maxdepth 1 -name 'package-*' \
-			#  -type d -print) | sed -e 's/^\.\/package-//'))
+			if [ -f "$validate_status_file" ]; then
+				validate_status=$(cat "$validate_status_file") || \
+				  panic "cannot get validate status"
+			else
+				validate_status=1
+			fi
+			if [ "$validate_status" -eq 0 ]; then
+				packages=($("$ari_info" -a "$project" packages)) || \
+				  panic "cannot get package list"
+			else
+				packages=()
+				printf "validation failed\n" >> "$tmp_file"
+			fi
 
 			if [ "$debug_level" -ge 1 ]; then
 				eecho "packages:"
@@ -268,90 +304,112 @@ while true; do
 				done
 			fi
 
-			printf "" > "$tmp_file" || panic
-			printf "%s\n\n" "Status: Commit $commit_id" >> "$tmp_file" || \
-			  panic
-
-			printf "Commit ID: $commit_id\n" >> "$tmp_file" || \
-			  panic
-#			printf "\n" >> "$tmp_file" || \
-#			  panic
-#			cat >> "$tmp_file" <<- EOF
-#			Commit ID: $commit_id
-#
-#			The following status values are possible:
-#			 * OK: no errors
-#			 * COM: at least one failure; operation completed
-#			 * INC: operation did not complete
-#			 * UNK: unknown error occurred
-#
-#			EOF
-#			[ $? -ne 0 ] || panic
-			printf "<pre>\n" >> "$tmp_file" || \
-			  panic
-			print_status >> "$tmp_file" || \
-			  panic
+			if [ "${#packages[@]}" -gt 0 ]; then
+				printf "<pre>\n" >> "$tmp_file" || \
+				  panic
+				print_status >> "$tmp_file" || \
+				  panic
+			fi
 			for package in "${packages[@]}"; do
 				package_dir="$workspace_dir/package-$package"
+				configure_status_file="$package_dir/configure/status"
+				generate_status_file="$package_dir/generate/status"
+
 				build_targets=($("$ari_info" \
 				  -a "$project" "package-$package/builds")) || \
 				  panic "cannot get build targets"
 				test_targets=($("$ari_info" \
 				  -a "$project" "package-$package/tests")) || \
 				  panic "cannot get test targets"
-				status_file="$package_dir/configure/status"
-				if [ -f "$status_file" ]; then
-					status="$(cat "$status_file")"
+
+				optional=$("$ari_info" \
+				  -a "$project" "package-$package/optional") || \
+				  panic "cannot get optional"
+
+				if [ -f "$generate_status_file" ]; then
+					generate_status="$(cat "$generate_status_file")"
 				else
-					status=
+					generate_status=
 				fi
 				print_status \
-				  "$package" "configure" "---" "$status" >> "$tmp_file" || \
+				  "$package" "generate" "---" "$generate_status" \
+				  >> "$tmp_file" || \
 				  panic
+
+				if [ -f "$configure_status_file" ]; then
+					configure_status="$(cat "$configure_status_file")"
+				else
+					configure_status=
+				fi
+				print_status \
+				  "$package" "configure" "---" "$configure_status" \
+				  >> "$tmp_file" || \
+				  panic
+
 				for target in "${build_targets[@]}"; do
-					status_file="$package_dir/build-$target/status"
-					if [ -f "$status_file" ]; then
-						status="$(cat "$status_file")"
+					build_status_file="$package_dir/build-$target/status"
+					if [ -f "$build_status_file" ]; then
+						build_status="$(cat "$build_status_file")"
 					else
-						status=
+						build_status=
 					fi
 					print_status \
-					  "$package" "build" "$target" "$status" >> "$tmp_file" || \
+					  "$package" "build" "$target" "$build_status" \
+					  >> "$tmp_file" || \
 					  panic
 				done
+
 				for target in "${test_targets[@]}"; do
-					status_file="$package_dir/test-$target/status"
-					if [ -f "$status_file" ]; then
-						status="$(cat "$status_file")"
+					# Do not provide information about optional test targets.
+					if [ "$optional" -ne 0 ]; then
+						continue
+					fi
+					test_status_file="$package_dir/test-$target/status"
+					if [ -f "$test_status_file" ]; then
+						test_status="$(cat "$test_status_file")"
 					else
-						status=
+						test_status=
 					fi
 					print_status \
-					  "$package" "test" "$target" "$status" >> "$tmp_file" || \
+					  "$package" "test" "$target" "$test_status" \
+					  >> "$tmp_file" || \
 					  panic
 				done
 			done
-			printf "</pre>\n" >> "$tmp_file" || \
-			  panic
+			if [ "${#packages[@]}" -gt 0 ]; then
+				printf "</pre>\n" >> "$tmp_file" || \
+				  panic "cannot append to temporary file"
+			fi
 			message="$(cat "$tmp_file")" || panic "cat failed"
-			eecho "##########"
-			eecho "$message"
-			eecho "##########"
+			echo
+			cat <<- EOF
+			======== START OF HUB ISSUE ==========
+			$message
+			======== END OF HUB ISSUE ==========
+			EOF
 
-			cp "$tmp_file" "$issue_file" || panic
+			cp "$tmp_file" "$issue_file" || panic "cannot copy file"
 
 			if [ "$enable_issues" -ne 0 ]; then
 				issue_url="$( (cd "$repo_dir" && \
 				  "$ari_hub" issue create -m "$message") )"
 			fi
 
-			echo "$commit_id" > "$old_commit_id_file" || panic
+			echo "$commit_id" > "$old_commit_id_file" || \
+			  panic "cannot update commit ID"
+
+			if [ -d "$old_workspace_dir" ]; then
+				rm -rf "$old_workspace_dir" || \
+				  panic "cannot remove old workspace directory"
+			fi
+			mv "$workspace_dir" "$old_workspace_dir" || \
+			  panic "cannot rename workspace directory"
 
 		fi
 
 		if [ "$first" -eq 0 ]; then
 			eecho "sleeping"
-			sleep 10
+			sleep 10 || panic "sleep failed"
 		fi
 	done
 
