ari_build: Added support for buildless packages. manual: Added information about the "none" value for the build_tool record. ari_demo: Changed the format of some of the program output. ari_pkgtrans: Added support for exists command.

diff --git a/bin/ari_demo b/bin/ari_demo
--- a/bin/ari_demo
+++ b/bin/ari_demo
@@ -34,6 +34,23 @@ ari_import="$cmd_dir/ari_import"
 ari_precheck="$cmd_dir/ari_precheck"
 ari_process="$cmd_dir/ari_process"
 
+default_pdf_viewer=evince
+
+execute_command()
+{
+	local command
+	command=("$@")
+	echo
+	echo "EXECUTING COMMAND: ${command[@]}"
+	echo "========== START OF COMMAND OUTPUT =========="
+	"${command[@]}"
+	local status
+	status=$?
+	echo "========== END OF COMMAND OUTPUT =========="
+	echo
+	return "$status"
+}
+
 usage()
 {
 	if [ $# -gt 0 ]; then
@@ -50,6 +67,7 @@ usage()
 
 	-p pdf_viewer
 	    Set the PDF viewer program to pdf_viewer.
+	    The default value is \$default_pdf_viewer.
 	-d output_directory
 	    Set the output directory to output_directory.
 	-D debug_level
@@ -70,16 +88,16 @@ all_names+=(hello_nif)
 all_names+=(hello_make)
 all_names+=(hello_cmake)
 
-default_pdf_viewer=xpdf
 dir=
 debug_level=0
 names=()
 view_report=1
+pdf_viewer="$default_pdf_viewer"
 
 while getopts D:d:p:n:R option; do
 	case "$option" in
 	p)
-		default_pdf_viewer="$OPTARG";;
+		pdf_viewer="$OPTARG";;
 	d)
 		dir=$((verbose + 1));;
 	D)
@@ -98,11 +116,13 @@ if [ -z "$dir" ]; then
 	dir=$(pwd) || panic
 fi
 
-pdf_viewer=$(type -P "$default_pdf_viewer")
-if [ $? -ne 0 ]; then
-	echo "cannot find PDF viewer $default_pdf_viewer"
-	echo "try specifying the viewer with the -p option"
-	panic "PDF viewer not found"
+if [ "$view_report" -ne 0 ]; then
+	pdf_viewer=$(type -P "$pdf_viewer")
+	if [ $? -ne 0 ]; then
+		echo "cannot find PDF viewer $pdf_viewer"
+		echo "try specifying the viewer with the -p option"
+		panic "PDF viewer not found"
+	fi
 fi
 
 if [ "${#names[@]}" -eq 0 ]; then
@@ -129,59 +149,35 @@ for name in "${names[@]}"; do
 		;;
 	esac
 
-	command=("$ari_precheck" -D "$debug_level"
-	  -v -p "$work_dir/precheck/" -t directory \
-	  "$example_dir/"$name-*)
-	cat <<- EOF
-	################################################################################
-	Running the command:
-	${command[@]}
-	################################################################################
-	EOF
-	"${command[@]}" || panic "${command[0]} failed"
+	command=("$ari_precheck" -D "$debug_level" -v -p "$work_dir/precheck/" \
+	  -t directory "$example_dir/"$name-*)
+	execute_command "${command[@]}" || \
+	  panic "${command[0]} failed"
 
 	if [ "$view_report" -ne 0 ]; then
-		cat <<- EOF
-		################################################################################
-		Showing report generated by ari_precheck (with PDF viewer $pdf_viewer)
-		################################################################################
-		EOF
 		for file in $work_dir/precheck/$name-*/report.pdf; do
+			echo "Showing report generated by ari_precheck (with PDF viewer $pdf_viewer)"
 			echo "Running PDF viewer for $file"
 			if [ ! -f "$file" ]; then
 				panic "cannot find file $file"
 			fi
-			"$pdf_viewer" "$file"
+			command=("$pdf_viewer" "$file")
+			execute_command "${command[@]}"
 		done
 	fi
 
-	command=("$ari_import" -D "$debug_level"
+	command=("$ari_import" -v -D "$debug_level"
 	  -p "$work_dir/assignments/" -t directory "$example_dir/"$name*)
-	cat <<- EOF
-	################################################################################
-	Running the command:
-	${command[@]}
-	################################################################################
-	EOF
-	"${command[@]}" || panic "${command[0]} failed"
+	execute_command "${command[@]}" || panic "${command[0]} failed"
 
-	command=("$ari_process" -D "$debug_level" "$work_dir/assignments/"*)
-	cat <<- EOF
-	################################################################################
-	Running the command:
-	${command[@]}
-	################################################################################
-	EOF
-	"${command[@]}" || panic "${command[0]} failed"
+	command=("$ari_process" -v -D "$debug_level" "$work_dir/assignments/"*)
+	execute_command "${command[@]}" || panic "${command[0]} failed"
 
 	if [ "$view_report" -ne 0 ]; then
-		cat <<- EOF
-		################################################################################
-		Showing report generated by ari_process (with PDF viewer $pdf_viewer)
-		################################################################################
-		EOF
 		for file in $work_dir/assignments/$name-*/report.pdf; do
-			"$pdf_viewer" "$file"
+			echo "Showing report generated by ari_process (with PDF viewer $pdf_viewer)"
+			command=("$pdf_viewer" "$file")
+			execute_command "${command[@]}"
 		done
 	fi
 
